- name: Reload transmission
  service:
    name: transmission-daemon
    state: reloaded

- name: Restart minidlna
  service:
    name: minidlna
    state: restarted

- name: Restart openvpn
  service:
    name: openvpn
    state: restarted

- name: Start protonvpn-ch
  service:
    name: protonvpn-ch
    state: started

- name: Start vpn-nat
  service:
    name: vpn-nat
    state: started
